### ISSUE TITLE
Error loading Module Error: Cannot find module '@medusajs/event-bus-local'

### ISSUE THREAD

**Issue by liangjaden** [Prn-Ice/medusa-docker#17]
medusa-server      | Error loading Module Error: Cannot find module '@medusajs/event-bus-local'
medusa-server      | Require stack:
medusa-server      | - /app/medusa/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js
medusa-server      | - /app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js
medusa-server      | - /usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js
medusa-server      | - /usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/index.js
medusa-server      | - /usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/cli.js
medusa-server      |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
medusa-server      |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
medusa-server      |     at Module.require (node:internal/modules/cjs/loader:999:19)
medusa-server      |     at require (node:internal/modules/cjs/helpers:102:18)
medusa-server      |     at getInternalModules (/app/medusa/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js:139:32)
medusa-server      |     at getModuleMigrations (/app/medusa/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js:227:25)
medusa-server      |     at getModuleSharedResources (/app/medusa/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js:266:57)
medusa-server      |     at /app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js:79:82
medusa-server      |     at step (/app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js:56:23)
medusa-server      |     at Object.next (/app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js:37:53) {
medusa-server      |   code: 'MODULE_NOT_FOUND',
medusa-server      |   requireStack: [
medusa-server      |     '/app/medusa/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js',
medusa-server      |     '/app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js',
medusa-server      |     '/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js',
medusa-server      |     '/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/index.js',
medusa-server      |     '/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/cli.js'
medusa-server      |   ]
medusa-server      | }
medusa-server      | Error loading Module Error: Cannot find module '@medusajs/cache-inmemory'
medusa-server      | Require stack:
medusa-server      | - /app/medusa/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js
medusa-server      | - /app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js
medusa-server      | - /usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js
medusa-server      | - /usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/index.js
medusa-server      | - /usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/cli.js
medusa-server      |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
medusa-server      |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
medusa-server      |     at Module.require (node:internal/modules/cjs/loader:999:19)
medusa-server      |     at require (node:internal/modules/cjs/helpers:102:18)
medusa-server      |     at getInternalModules (/app/medusa/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js:139:32)
medusa-server      |     at getModuleMigrations (/app/medusa/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js:227:25)
medusa-server      |     at getModuleSharedResources (/app/medusa/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js:266:57)
medusa-server      |     at /app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js:79:82
medusa-server      |     at step (/app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js:56:23)
medusa-server      |     at Object.next (/app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js:37:53) {
medusa-server      |   code: 'MODULE_NOT_FOUND',
medusa-server      |   requireStack: [
medusa-server      |     '/app/medusa/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js',
medusa-server      |     '/app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js',
medusa-server      |     '/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js',
medusa-server      |     '/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/index.js',
medusa-server      |     '/usr/local/share/.config/yarn/global/node_modules/@medusajs/medusa-cli/cli.js'
medusa-server      |   ]
medusa-server      | }
medusa-server      | TypeError: typeorm_1.DataSource is not a constructor
medusa-server      |     at /app/medusa/node_modules/@medusajs/medusa/dist/loaders/database.js:64:42
medusa-server      |     at step (/app/medusa/node_modules/@medusajs/medusa/dist/loaders/database.js:33:23)
medusa-server      |     at Object.next (/app/medusa/node_modules/@medusajs/medusa/dist/loaders/database.js:14:53)
medusa-server      |     at /app/medusa/node_modules/@medusajs/medusa/dist/loaders/database.js:8:71
medusa-server      |     at new Promise (<anonymous>)
medusa-server      |     at __awaiter (/app/medusa/node_modules/@medusajs/medusa/dist/loaders/database.js:4:12)
medusa-server      |     at /app/medusa/node_modules/@medusajs/medusa/dist/loaders/database.js:56:12
medusa-server      |     at /app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js:82:61
medusa-server      |     at step (/app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js:56:23)
medusa-server      |     at Object.next (/app/medusa/node_modules/@medusajs/medusa/dist/commands/migrate.js:37:53)
medusa-storefront  | Browserslist: caniuse-lite is outdated. Please run:
medusa-storefront  |   npx browserslist@latest --update-db
medusa-storefront  |   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
medusa-server      | Successfully compiled 0 files with Babel (6ms).
medusa-server      | [medusa-config] ⚠️ jwt_secret not found. fallback to either cookie_secret or default 'supersecret'.
medusa-server      | [medusa-config] ⚠️ cookie_secret not found. fallback to either cookie_secret or default 'supersecret'.
medusa-server      | [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND vu1ogr
medusa-server      |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:72:26)
medusa-server      | error:   An error occurred while connecting to Redis:
medusa-server      |  Error: Connection is closed.
medusa-server      | - Initializing models
medusa-server      | 
medusa-server      | ✔ Models initialized – 80ms
medusa-server      | - Initializing plugin models
medusa-server      | 
medusa-server      | ✔ Plugin models initialized – 5ms
medusa-server      | - Initializing strategies
medusa-server      | 
medusa-server      | ✔ Strategies initialized – 53ms
medusa-server      | - Initializing modules
medusa-server      | 
medusa-server      | error:   Could not resolve required module: EventBusModuleService. Error: Make sure you have installed the default package: @medusajs/event-bus-local
medusa-server      | 
medusa-server      | error:   Error starting server
medusa-server      | Error: Make sure you have installed the default package: @medusajs/event-bus-local
medusa-server      |     at loadInternalModule (/app/medusa/node_modules/@medusajs/modules-sdk/dist/loaders/utils/load-internal.js:42:24)
medusa-server      |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
medusa-server      |     at async loadModule (/app/medusa/node_modules/@medusajs/modules-sdk/dist/loaders/module-loader.js:36:12)
medusa-server      |     at async moduleLoader (/app/medusa/node_modules/@medusajs/modules-sdk/dist/loaders/module-loader.js:40:36)

**Comment by toru-takahashi** [comment]
As i tried, I tried a couple of changes based on the following issue.

- https://github.com/medusajs/medusa/discussions/3430

Then it works well.

**Comment by Peter-Spi** [comment]
Hi [liangjaden](https://github.com/liangjaden), I stumbled upon the same error, have you managed to solve it somehow?

**Comment by Dalvae** [comment]
Same error here.

**Comment by SalcidoJesus** [comment]
any solution?

**Comment by Prn-Ice** [comment]
Hi, sorry to hear about the issue, I will try to fix it when i get some free time.

**Comment by ramzlab000** [comment]
> Hi, sorry to hear about the issue, I will try to fix it when i get some free time.

Hi there,

Thank you for the setup. I've been frantically looking for one and found this. I managed to get to build but ran into the same this as possibly others. Here are some notes;

I had to comment out the following lines from `backend/.dockerignore` to get it to build

```
data/
yarn.lock 
```

However, the database seed fails when I try the following

`docker exec medusa-server Medusa seed -f ./data/seed.json`

please note the medusa is has to be all small letters too!

Thanks for your help

**Comment by costarotela** [comment]
HI, Sorry i had a same problem, with event-bus-local, i don't know what to do, there are anybody that help me PLEASE

**Comment by costarotela** [comment]
rebuilding the image with the changes made using the --no-cache flag stops with an error
